### ISSUE TITLE
Allow activation & deactivation of mocks

### ISSUE THREAD

**Issue by iridakos** [iridakos/duckrails#1]
Add flag to Mock model and don't register the route if it's deactivated.

**Comment by GustavoCaso** [comment]
Hy @iridakos is anyone working on this one ?

**Comment by iridakos** [comment]
Hi @GustavoCaso, I plan to work on this the following days. Adding tests at the moment.

**Comment by GustavoCaso** [comment]
Hi @iridakos. My question was related in favor on helping you some issues, if you want of course.

**Comment by iridakos** [comment]
Of course, thank you! Do you want to work on this one?

**Comment by GustavoCaso** [comment]
Sure, but if you already working on this one I don't want to break your process maybe there is another one I can help you

**Comment by iridakos** [comment]
I haven't started working on it yet so you can start it instead.

**Comment by GustavoCaso** [comment]
Great if I need any help I will ping you. 

Thanks :+1:

**Comment by iridakos** [comment]
Hi @GustavoCaso,

I'm going to start working on this issue this weekend if you don't mind. I need it in order to continue on another issue (#9).

Thanks!

**Comment by GustavoCaso** [comment]
@iridakos Sorry I have been swamp with work lately. I hope I can in the close future.

**Comment by iridakos** [comment]
@GustavoCaso No worries! Already implemented :D
