### ISSUE TITLE
Multi-threading

### ISSUE THREAD

**Issue by hambonis** [iridakos/duckrails#16]
Whenever you do a sleep or proxy data from another service, all mocks and the UI wait for the current operation to finish.

**Comment by iridakos** [comment]
Correct. I will update the documentation to obtain info on setting up more thins or unicorn with multiple workers to resolve this issue.

Thanks for the feedback @hambonis

**Comment by hambonis** [comment]
Thanks a bunch!

**Comment by iridakos** [comment]
@hambonis Done!

You may use puma (see README) or any other server with concurrency/parallelism you prefer and you should be fine.
Let me know if you have any problems.
