### ISSUE TITLE
possible styling issues

### ISSUE THREAD

**Issue by phamdt** [iridakos/duckrails#17]
i've setup the application and so far it seems to be working, however the styling is definitely off. parts of the page, particularly the header and footer look like the css is mostly missing. my first guess is that it has to do with differences in the foundation-rails gem. what gem version works for you guys?

**Comment by iridakos** [comment]
Well, the repo contains the Gemfile.lock file so the version of the foundation gem can't be the problem unless you modified it. Can you please provide more information (like browser console network errors related to css)?

**Comment by iridakos** [comment]
Hey @phamdt,

I'm closing this issue. I made some changes for v2.0.0
You can either try with the new version or pull the new docker image for duckrails from [docker hub](https://hub.docker.com/r/iridakos/duckrails/) and re-open in case you still have the problem.

Thanks!
