### ISSUE TITLE
Please make more accessible

### ISSUE THREAD

**Issue by johngluckmdsol** [iridakos/duckrails#18]
This looks really cool.  Can you make a docker image out of it so I don't have to clone the repo?

**Comment by iridakos** [comment]
Good idea.

**Comment by iridakos** [comment]
@johngluckmdsol I created a [docker hub](https://hub.docker.com/r/iridakos/duckrails/) repository with automated builds.
Let me know if you have any problems using it.

PS: I am no docker expert so feel free to give suggestions on the Dockerfile I created.
