### ISSUE TITLE
Allow users to move mock under a scope

### ISSUE THREAD

**Issue by nicolas-besnard** [iridakos/duckrails#21]
If I've a lot of mock, it might be nice to be able to prepend the route of all my mocks by something (e.g add `/api/v1` to some mock).

I'd love to have a view with all my mocks and drag them to build my desired path.
It might also be interesting to use this feature to create a "common" configuration (e.g. common headers)

If you'd like this feature, I'm happy to propose an implementation.

Cheers :)

**Comment by iridakos** [comment]
Hey @nicolas-besnard ,

Nice feature which is already under development :D (issues #7 #8).

Each mock will have a namespace with the default one mapping to the root path of the application.

Feel free to propose your implementation, you might have thought something better than I have.

Thanks a lot!

**Comment by nicolas-besnard** [comment]
Happy to contribute if the code is on a branch :)

**Comment by iridakos** [comment]
I'll update this issue once I push to the branch (hopefully till the end of next week)

Thanks again!

**Comment by nicolas-besnard** [comment]
Any news on that?
