### ISSUE TITLE
Allow user to save response bodoy

### ISSUE THREAD

**Issue by nicolas-besnard** [iridakos/duckrails#26]
Hi,

When developing, I'm using Duckrails to mock my API. Sometimes I'd like the same endpoint to respond with a different body (and/or a different status code).

Do you think this could make sense to add this feature?

It can wether be with a "special" query (e.g. `?duckrails_body_name=no_user`) or on the web interface?

I'm happy to provide a PR if you are happy with this.

**Comment by iridakos** [comment]
@nicolas-besnard If I understand your request, this feature is already supported. In the advanced tab you can configure both the body and the status code. Check the documentation [here](https://github.com/iridakos/duckrails/wiki/Using-the-mock-form). With dynamic ruby for example you can parse the request parameters and decide to respond accordingly.

**Note:** I'm closing this issue unless you get back to me with an update in case I didn't understand/cover your request.
