### ISSUE TITLE
Help execute Duckrails in Docker TTY

### ISSUE THREAD

**Issue by renasti** [iridakos/duckrails#46]
Hi Friends, i run Duckrails with docker, more i get error below:

`mesg: ttyname failed: Inappropriate ioctl for device`

Command executed: 
`docker run -p 8080:80 -v /Users/renato/duck:/opt/duckrails/db iridakos/duckrails:release-v2.1.0`

The output the command above: https://gist.github.com/renasti/09046677fc35a45f4ace54be250a356f

Im using Mac OS X

**Comment by iridakos** [comment]
Hi @renasti ,

The first part of the volume parameters you pass (`/Users/renato/duck`) should be the name of the volume and not a path.

> In the case of named volumes, the first field is the name of the volume, and is unique on a given host machine. For anonymous volumes, the first field is omitted.

You should try using a valid volume name (like: `duckrails`) instead?
