### ISSUE TITLE
Create mock with return alternative

### ISSUE THREAD

**Issue by renasti** [iridakos/duckrails#47]
How to configure fot accept parameter empty? My ideia is return default value in case
I need create a mock example: /user/v1/user-credential 
**with params:**
document = 123
**with return:**
```
{
   "document" : "123"
}
```
But, i need create same mock name **/user/v1/user-credential** with return alternative, example:
**with params**
document = 092
**with return**
```
{
   "document" : "092",
   "name" : "Renato"
}
```
How to make this? I look the documentation, but not found solution.

**Comment by iridakos** [comment]
Hi @renasti 
You can do something like the following given you have chosen embedded ruby as the body type:

```ruby
<%=
  result = { document: @parameters[:document] }
  
  if @parameters[:document] == '092'
    result[:name] = 'Renato'
  end

  result.to_json
%>
```
