### ISSUE TITLE
Layout missing

### ISSUE THREAD

**Issue by nicoschuele** [iridakos/duckrails#5]
After `bundle install` and `rake db:setup`, when I run my rails server, the layout is broken (missing). I get errors such as this one:

```
Started GET "/javascripts/vendor/modernizr.js" for ::1 at 2016-03-19 08:41:12 +0100

ActionController::RoutingError ((╯°□°）╯︵ ┻━┻ : No route matches [GET] "/javascripts/vendor/modernizr.js"):
```

Tool looks really useful and looking forward to use it!

**Comment by iridakos** [comment]
Thank you,

How do you start the application?
The example you give should mapped under `/assets`:
`Started GET "/assets/vendor/modernizr.self-74da3245...`

**Comment by nicoschuele** [comment]
I start it with `rails s`.

When looking at the repository, I can't find any `vendor` directory. Did I miss something?

**Comment by iridakos** [comment]
I can't reproduce it... Can you try executing the rails commands prepending `bundle exec`?

**Comment by iridakos** [comment]
Can't reproduce.

**Comment by oliver-whiteman** [comment]
I get this same issue as well:

Started GET "/javascripts/vendor/modernizr.js" for ::1 at 2016-04-25 14:06:34 +0100

ActionController::RoutingError (No route matches [GET] "/javascripts/vendor/modernizr.js"):

**Comment by oliver-whiteman** [comment]
This is the url it is trying to hit:

http://localhost:3000/javascripts/vendor/modernizr.js

**Comment by TImPDaley** [comment]
I have the exact same issue

**Comment by iridakos** [comment]
@nicoschuele @oliver-whiteman @TImPDaley There have been some changes in the code and probably you won't face the issue again. If you still get the error, let me know to further investigate. Thank you for your feedback.
