### ISSUE TITLE
How to use query parameters?

### ISSUE THREAD

**Issue by Banjerr** [iridakos/duckrails#56]
Is there currently a way to use optional query parameters for an endpoint? 

For example, I would like to be able to use

`localhost/v1/route?optional=1&dynamic=1`

and still be able to hit `localhost/v1/route` without the query parameters...

When I attempt to add a query parameter to a mock endpoint then it is automatically "required", or else the endpoint is no longer found when trying to hit it.

**Comment by iridakos** [comment]
Hi @Banjerr,

You don't have to specify any parameters in the URL.

For your case I configured the following mock:
![image](https://user-images.githubusercontent.com/9477868/69720336-1148e300-111b-11ea-9d2f-ee413b903268.png)

with response body resolved to the parameters:
![image](https://user-images.githubusercontent.com/9477868/69720367-1c037800-111b-11ea-8a06-47554ff0effd.png)

and I can hit /v1/route with parameters:

![image](https://user-images.githubusercontent.com/9477868/69720393-2a519400-111b-11ea-9c6a-26a87b305209.png)

or without parameters:
![image](https://user-images.githubusercontent.com/9477868/69720516-76043d80-111b-11ea-9f72-99aab2611005.png)

Feel free to re-open this issue in case I didn't answer to your question.

Bye
