### ISSUE TITLE
Docker absolute volume path and runtime error

### ISSUE THREAD

**Issue by pun-ky** [iridakos/duckrails#58]
```
docker run --name=example_iridakos.duckrails.release-v2.1.5 -v=/Users/krystian.panek/Projects/gradle-aem-multi/duckrails:/opt/duckrails/db -p=8080:80 --rm iridakos/duckrails:release-v2.1.5
WARNING: Environment variable SECRET_KEY_BASE has not been set - Setting a random SECRET_KEY_BASE
rake aborted!
ActiveRecord::StatementInvalid: Could not find table 'mocks'
/opt/duckrails/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/sqlite3_adapter.rb:501:in `table_structure'
/opt/duckrails/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/sqlite3_adapter.rb:375:in `columns'
/opt/duckrails/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/schema_cache.rb:43:in `columns'
/opt/duckrails/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/attributes.rb:93:in `columns'
/opt/duckrails/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/attributes.rb:98:in `columns_hash'
/opt/duckrails/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/relation/delegation.rb:48:in `columns_hash'
```

but when I use just `duckrails` on the left side of volume it works.

```
docker run --name=example_iridakos.duckrails.release-v2.1.5 -v=duckrails:/opt/duckrails/db -p=8080:80 --rm iridakos/duckrails:release-v2.1.5
```

still when using absolute path or relative path, in both cases seems that volume is working / file `duckrails/production.sqlite3` is created... so that seems that is is something wrong later on DuckRails runtime side.

this is blocking me in case of using Duckrails on Windows on which I need to support Docker Toolbox in which absolute volume paths usage is essential.

it would be nice to have it fixed :)

greetings, Krystian

**Comment by pun-ky** [comment]
also does not work when using Swarm :/

![image](https://user-images.githubusercontent.com/10673561/70524723-11e36f80-1b46-11ea-91c9-98df22f86c08.png)

**Comment by pun-ky** [comment]
is there any chance to have it fixed within next days? sorry I have no Ruby knowledge to be able to fix it by myself :/

**Comment by pun-ky** [comment]
any volunteers to help with that? :)

**Comment by ChristianHeimke** [comment]
@pun-ky 

I just stumbled over your issue, maybe you found the answer finally ;-) If not, this will maybe help you out:

You're calling docker with the wrong parameters:

```
# wrong
docker run --name=example_iridakos.duckrails.release-v2.1.5 -v=/Users/krystian.panek/Projects/gradle-aem-multi/duckrails:/opt/duckrails/db -p=8080:80 --rm iridakos/duckrails:release-v2.1.5

# right
docker run --name=example_iridakos.duckrails.release-v2.1.5 -v /Users/krystian.panek/Projects/gradle-aem-multi/duckrails:/opt/duckrails/db -p 8080:80 --rm iridakos/duckrails:release-v2.1.5
``` 
What's the diff? You shouldn't use `=` on short params like `-p`  or `-v`. If you want to use it, you need to pass the double dash and the "full wording", e.g. `--volume=...` or `--port=...`

Maybe this will help :) I just tested the command from the docs: 
```
docker run -p 8080:80 -v duckrails:/opt/duckrails/db iridakos/duckrails:latest
``` 
and it worked out of the box.

**Comment by pun-ky** [comment]
yep, most probably you are right. I will test it out and let you know if it works.
thank you very much for explanation.

**Comment by ChristianHeimke** [comment]
yes, you're right.

I'm just guessing, but maybe it's related to the `docker-entrypoint.sh`, which will bootstrap the database and tables. maybe you can check out the difference of your file and the provided compose files:

* https://github.com/iridakos/duckrails/blob/master/docker-compose.yml
* https://github.com/iridakos/duckrails/blob/master/docker-compose-single.yml

I've tested the first one and it worked as expected. Maybe.. it is also related to the 2.1.5 version - I've not tested this specific one, just the lastest and the compose file with building the current source.

**Comment by pun-ky** [comment]
Good point, I will do that. @ChristianHeimke thx

**Comment by pun-ky** [comment]
I guess it could be somehow addressed by providing correct docker compose file so does not affect directly Duckrails app.
