### ISSUE TITLE
No route matches

### ISSUE THREAD

**Issue by rarhs** [iridakos/duckrails#6]
Hi, I am following the github example. After creating a new mock and save the route, when I go to /posts on cloud9 or http://localhost:3000/posts on my local machine I get this error: ```No route matches [GET] "/posts"```. Is there something I am missing?

**Comment by iridakos** [comment]
Hi, the example's route is set to be served via post method and you try to access it via get method.

**Comment by rarhs** [comment]
Thanks for your clarification.
